#루시와 엘라 찾기
SELECT ANIMAL_ID,NAME,SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy','Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
#IN 사용


#이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%EL%' 
    AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME
#LIKE % 넣기

#중성화 여부 파악하기
SELECT ANIMAL_ID, NAME,
(CASE WHEN SEX_UPON_INTAKE LIKE '%Neutered%' THEN 'O' 
    WHEN SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O' 
    ELSE 'X'
    END) AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
#CASE WHEN ~ THEN ~ 끝은 END 후에 괄호 기억하기 

#오랜기간 보호한 동물(2)
SELECT INS.ANIMAL_ID,INS.NAME #, DATEDIFF(OUTS.DATETIME, INS.DATETIME) AS '보호기간' 
FROM ANIMAL_INS AS INS, (SELECT ANIMAL_ID,DATETIME
     FROM ANIMAL_OUTS
     ) AS OUTS 
WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID 
ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC
LIMIT 2
#LIMIT n을 통해서 특정 개수의 행 출력 

#DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS '날짜'
FROM ANIMAL_INS
#DATE_FORMAT 형식 확인
